### ISSUE TITLE
analyzer.json type "constant" throws UnsupportedAnalyzerType exception

### ISSUE THREAD

**Issue by sai-kopparthi** [returntocorp/cli#25]
## What did you expect to happen?

I am trying to run the analyzer locally on left-pad cloned repo got the following error while running the analyzer can you please help me out with this issue .

r2c run ~/test-repos/left-pad
🏃 Starting to run analyzer...

Resolving dependencies
🔨 Building docker container
✔️  Successfully built docker.
🔎 Running analysis on `/home/sai/test-repos/left-pad`
❌ There was an exception: AnalyzerType.constant
Please file a bug report at https://github.com/returntocorp/cli/issues/new/choose
with the information provided in /home/sai/.r2c/_logs/r2c-debug.log

## Error log

2019-04-15 11:23:32,398 - r2c.cli - INFO - ============================================================
2019-04-15 11:23:32,399 - r2c.cli - INFO - System: Linux/4.18.0-17-generic
2019-04-15 11:23:32,400 - r2c.cli - INFO - Python: 3.6.7
2019-04-15 11:23:32,400 - r2c.cli - INFO - Timestamp: 2019-04-15 11:23:32.400157
2019-04-15 11:23:32,429 - r2c.cli - INFO - Docker: Docker version 18.09.5, build e8ff056
2019-04-15 11:23:32,429 - r2c.cli - INFO - ============================================================

2019-04-15 11:23:34,269 - r2c.cli - ERROR - There was an exception
Traceback (most recent call last):
  File "/home/sai/.local/lib/python3.6/site-packages/r2c/cli/__main__.py", line 21, in <module>
    cli(obj={}, prog_name="r2c")
  File "/home/sai/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sai/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sai/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sai/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sai/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/sai/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sai/.local/lib/python3.6/site-packages/r2c/cli/commands/run.py", line 196, in run
    env_args_dict=env_args_dict,
  File "/home/sai/.local/lib/python3.6/site-packages/r2c/lib/run.py", line 348, in run_analyzer_on_local_code
    env_args_dict=env_args_dict,
  File "/home/sai/.local/lib/python3.6/site-packages/r2c/l
ib/analyzer.py", line 331, in full_analyze_request
    git_url, commit_hash, specified_dependency
  File "/home/sai/.local/lib/python3.6/site-packages/r2c/lib/analyzer.py", line 277, in analysis_key
    raise UnsupportedAnalyzerType(analyzer_type)
r2c.lib.analyzer.UnsupportedAnalyzerType: AnalyzerType.constant

## Specs

- OS: ubuntu 18.04
- Python Version : Python 3.6.7
- Docker Version 8.09.5, build e8ff056
- Screen size (if appropriate)

[whitespace.tar.gz](https://github.com/returntocorp/cli/files/3081599/whitespace.tar.gz)

**Comment by sai-kopparthi** [comment]
Can you please help me out with this issue. 

Best,
Sai Kopparthi

**Comment by dlukeomalley** [comment]
Thanks for filing this! I think the issue is with your `analyzer.json` file's `type` field. Changing the value from `constant` to `commit` should fix things for you!

```
{
    "analyzer_name": "ecs260-31/whitespace",
    "author_name": "sai",
    "author_email": "skopparthi@ucdavis.edu",
    "version": "0.0.1",
    "spec_version": "1.2.0",
    "dependencies": {
        "public/source-code": "*"
    },
    "type": "commit",
    "output": {
        "type": "json"
    },
    "deterministic": true
}
```

**Comment by sai-kopparthi** [comment]
Got it thanks . Didn't realize that one.
