### ISSUE TITLE
friendlier output if you fail to provide a proper output file

### ISSUE THREAD

**Issue by ievans** [returntocorp/cli#56]
If we can't find the output.json (or output fs directory for a filesystem analyzer), we ought to display a friendlier message than "there was an exception" (see current output below):

```
There was an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/__main__.py", line 14, in <module>
    cli(obj={}, prog_name="r2c")
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/commands/run.py", line 268, in run
    reset_cache=reset_cache,
  File "/usr/local/lib/python3.7/site-packages/r2c/lib/run.py", line 462, in run_analyzer_on_local_code
    env_args_dict=env_args_dict,
  File "/usr/local/lib/python3.7/site-packages/r2c/lib/analyzer.py", line 406, in full_analyze_request
    specified_dependency, git_url, commit_hash, mount_folder
  File "/usr/local/lib/python3.7/site-packages/r2c/lib/analyzer.py", line 484, in upload_output
    git_url, commit_hash, specified_analyzer, output_file_path
  File "/usr/local/lib/python3.7/site-packages/r2c/lib/filestore.py", line 131, in put
    shutil.copy(source, target_path)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/analysis/XXXXXXX__0.0.1__20190601T003457.518357/output/output.json'
✘ There was an exception: [Errno 2] No such file or directory: '/tmp/analysis/XXXXXXX__20190601T003457.518357/output/output.json'
Please file a bug report at https://github.com/returntocorp/cli/issues/new/choose
with the information provided in /Users/ine/.r2c/_logs/r2c-debug.log
```

**Comment by ulziibay** [comment]
@ievans how do you reproduce this?

**Comment by ievans** [comment]
@ulziibay write an analyzer that doesn't produce an output.json file in the right spot
