### ISSUE TITLE
r2c push failed with "Invalid version string" error

### ISSUE THREAD

**Issue by dan5382** [returntocorp/cli#6]
![image](https://user-images.githubusercontent.com/2009327/55376189-230eb380-54c4-11e9-9ba8-7733b89a940f.png)

```
2019-04-01 21:18:36,566 - r2c.cli - INFO - ============================================================
2019-04-01 21:18:36,576 - r2c.cli - INFO - System: Darwin/18.2.0
2019-04-01 21:18:36,576 - r2c.cli - INFO - Python: 3.7.2
2019-04-01 21:18:36,576 - r2c.cli - INFO - Timestamp: 2019-04-01 21:18:36.576836
2019-04-01 21:18:36,790 - r2c.cli - INFO - Docker: Docker version 18.09.2, build 6247962
2019-04-01 21:18:36,791 - r2c.cli - INFO - ============================================================

2019-04-01 21:18:37,354 - r2c.cli - ERROR - There was an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/__main__.py", line 21, in <module>
    cli(obj={}, prog_name="r2c")
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/commands/push.py", line 75, in push
    analyzer_directory, ctx
  File "/usr/local/lib/python3.7/site-packages/r2c/cli/util.py", line 224, in find_and_open_analyzer_manifest
    return (AnalyzerManifest.from_json_str(raw_manifest), manifest_parent_dir)
  File "/usr/local/lib/python3.7/site-packages/r2c/lib/manifest.py", line 343, in from_json_str
    return AnalyzerManifest.from_json(json_obj)
  File "/usr/local/lib/python3.7/site-packages/r2c/lib/manifest.py", line 325, in from_json
    Version(json_obj["version"]),
  File "/usr/local/lib/python3.7/site-packages/semantic_version/base.py", line 77, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/usr/local/lib/python3.7/site-packages/semantic_version/base.py", line 205, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '0.1.o'
```

my theory: we have version 0.1.0 already uploaded. Even changing the name of the containing folder doesn't' seem to work.... gonna change the version and see if this fixes it.

**Comment by dan5382** [comment]
Upping the version worked... we need to fix this pretty quick.

**Comment by dan5382** [comment]
![image](https://user-images.githubusercontent.com/2009327/55376389-07f07380-54c5-11e9-9310-f675f0289243.png)

So the system respected my name change in the drop down but it still registered this as 'minifinder' in the backend? i dunno. weird.

**Comment by dlukeomalley** [comment]
Thanks for filing this! The root cause looks to be that you have an `o` instead of `0` in your version string, which breaks the [SemVer spec](https://semver.org/).

I'm thinking the fix could be as simple as adding some additional context to the error message, what do you think?

> Invalid version string: '0.1.o'

vs. 

> Invalid version string: '0.1.o'. Please check that it follows the SemVer spec (https://semver.org/).

**Comment by dan5382** [comment]
thanks for the quick answer! yeahhhh i noticed my mistake yesterday... coding at night may be more my problem...

**Comment by ulziibay** [comment]
We resolved this with  0016 release, it will validate analyzer name and handle errors properly
