### ISSUE TITLE
List output is handled poorly in CLI 0016

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/cli#7]
## What happened?

❌ There was an exception: 'list' object has no attribute 'get'

## What did you expect to happen?

To handle the error properly

## To reproduce

(cli-dev) ulziibayars-MacBook-Pro:cli_0016_actual ulziibayarotgonbaatar$ r2c -v run ~/Workspace/left-pad 

Write dummy analyzer that outputs
```
[{"filePath":"/analysis/inputs/public/source-code/src/format-output.js","messages":[{"ruleId":"complexity","severity":1,"message":"Arrow function has a complexity of 2.","line":11,"column":5,"nodeType":"ArrowFunctionExpression","messageId":"complex","endLine":26,"endColumn":6}],"errorCount":0,"warningCount":1,"fixableErrorCount":0,"fixableWarningCount":0,"source":"const fs = require('fs');\nconst process = require('process');\n\nlet r2c_results = {\n    results: [],\n    errors: []\n};\n\nlet eslint_report = JSON.parse(fs.readFileSync(process.argv[2]));\neslint_report.forEach(\n    file_report => {\n        try {\n            r2c_results.results.push({\n                check_id: \"complexity\",\n                path: file_report.filePath,\n                extra: {\n                    complexities: file_report.messages.map(report => report.message.match(/Function.*has a complexity of (\\d+)\\./)[1])\n                }\n            })\n        } catch (error) {\n            r2c_results.errors.push({\n                message: \"Exception parsing eslint report\",\n                data: {\"msg\": error.message, \"stack\": error.stack}\n            });\n        }\n    }        \n);\n\ntry {\n    let sloc_report = JSON.parse(fs.readFileSync(process.argv[3]));\n    sloc_report.byExt.js.files.forEach(\n        file_report => {\n            r2c_results.results.push({\n                check_id: \"sloc\",\n                path: file_report.path,\n                extra: file_report.stats\n            });\n        }\n    );\n} catch (error) {\n    r2c_results.errors.push({\n        message: \"Exception parsing sloc report\",\n        data: {\"msg\": error.message, \"stack\": error.stack}\n    });\n}\n\nfs.writeFileSync(\"/analysis/output/output.json\", JSON.stringify(r2c_results, null, '\\t'));\n\n"}]
```

## Error log

🏃 Starting to run analyzer...
Resolving dependencies
🔨 Building docker container
Sending build context to Docker daemon  2.423MB
Step 1/7 : FROM ubuntu:17.10
 ---> e211a66937c6
Step 2/7 : RUN apt update && apt install -y python3   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 1d5496ab0c76
Step 3/7 : RUN groupadd -r analysis && useradd -m --no-log-init --gid analysis analysis
 ---> Using cache
 ---> 811ba69161b8
Step 4/7 : USER analysis
 ---> Using cache
 ---> 4f2622c745c4
Step 5/7 : COPY src /analyzer
 ---> adcbe9fadc84
Step 6/7 : WORKDIR /
 ---> Running in d65517349735
Removing intermediate container d65517349735
 ---> de265b11b1aa
Step 7/7 : CMD ["/analyzer/analyze.sh"]
 ---> Running in d85c821a8138
Removing intermediate container d85c821a8138
 ---> ef499735f3ea
[Warning] One or more build-args [UNAME GID UID] were not consumed
Successfully built ef499735f3ea
Successfully tagged 338683922796.dkr.ecr.us-west-2.amazonaws.com/massive-r2c/cli_0016_actual:0.0.1
✔️  Successfully built docker.
🔎 Running analysis on `/Users/ulziibayarotgonbaatar/Workspace/left-pad`
INFO:r2c.lib.run:Analyzer manifest already present in registry
INFO:r2c.lib.run:"Uploading" (moving) code directory as the output of all cloners. Cloner versions: [public/source-code:0.0.1]
INFO:r2c.lib.run:Using default workdir
INFO:r2c.lib.run:Created tempdir at /tmp/local-analysis/y1q0o8xi
INFO:r2c.lib.analyzer:Filesystem output type. Tarring output for uploading...
INFO:r2c.lib.analyzer:Uploading /tmp/local-analysis/y1q0o8xi/output/fs.tar.gz to r2c-pipeline-analysis-output with key public/source-code/0.0.1/kFGctQnZlx2LvFWblZXZ0N3Lt92YuIWdoRXan9yL6MHc0RHa/2fca6157fcca165438e0f9495cf0e5a4e6f71349/output.tar.gz
INFO:r2c.lib.analyzer:All analyzers that will be run, in order: 
	0: public/source-code:0.0.1 parameters:{}
	1: r2c/cli_0016_actual:0.0.1 parameters:{}
INFO:r2c.lib.analyzer:Analysis for https://github.com/stevemao/left-pad 2fca6157fcca165438e0f9495cf0e5a4e6f71349 338683922796.dkr.ecr.us-west-2.amazonaws.com/massive-public/source-code:0.0.1 already exists. Keeping old analysis report
INFO:r2c.lib.analyzer:Running: r2c/cli_0016_actual, 0.0.1...
INFO:r2c.lib.analyzer:Setting up volumes for analyzer container.
INFO:r2c.lib.analyzer:Will mount: /tmp/analysis/cli_0016_actual__0.0.1__2fca6157fcca165438e0f9495cf0e5a4e6f71349__20190402T050426.184958
INFO:r2c.lib.analyzer:Loading dependencies' outputs: [public/source-code:0.0.1 parameters:{}]
INFO:r2c.lib.analyzer:Loading output of public/source-code:0.0.1 parameters:{}
INFO:r2c.lib.analyzer:Has image_id: 338683922796.dkr.ecr.us-west-2.amazonaws.com/massive-public/source-code:0.0.1
INFO:r2c.lib.analyzer:Retrieving dependency output from s3 with key public/source-code/0.0.1/kFGctQnZlx2LvFWblZXZ0N3Lt92YuIWdoRXan9yL6MHc0RHa/2fca6157fcca165438e0f9495cf0e5a4e6f71349/output.tar.gz
INFO:r2c.lib.analyzer:Extracting filesystem dependency
INFO:r2c.lib.analyzer:Done setting up output of dependency public/source-code:0.0.1 parameters:{}.
INFO:r2c.lib.analyzer:Running container 338683922796.dkr.ecr.us-west-2.amazonaws.com/massive-r2c/cli_0016_actual:0.0.1 (memory limit: 2G): 
	: debug with docker run  --volume "/tmp/analysis/cli_0016_actual__0.0.1__2fca6157fcca165438e0f9495cf0e5a4e6f71349__20190402T050426.184958:/analysis" 338683922796.dkr.ecr.us-west-2.amazonaws.com/massive-r2c/cli_0016_actual:0.0.1
INFO:r2c.lib.analyzer:Analyzer finished running.
INFO:r2c.lib.analyzer:Uploading analyzer log
INFO:r2c.lib.analyzer:Uploading analyzer output
INFO:r2c.lib.analyzer:Uploading /tmp/analysis/cli_0016_actual__0.0.1__2fca6157fcca165438e0f9495cf0e5a4e6f71349__20190402T050426.184958/output/output.json to r2c-pipeline-analysis-output with key r2c/cli_0016_actual/0.0.1/kFGctQnZlx2LvFWblZXZ0N3Lt92YuIWdoRXan9yL6MHc0RHa/2fca6157fcca165438e0f9495cf0e5a4e6f71349/output.json
ERROR:r2c.cli:There was an exception
Traceback (most recent call last):
  File "/Users/ulziibayarotgonbaatar/Workspace/echelon-backend/r2c/cli/r2c/cli/__main__.py", line 21, in <module>
    cli(obj={}, prog_name="r2c")
  File "/Users/ulziibayarotgonbaatar/.virtualenvs/cli-dev/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ulziibayarotgonbaatar/.virtualenvs/cli-dev/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ulziibayarotgonbaatar/.virtualenvs/cli-dev/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ulziibayarotgonbaatar/.virtualenvs/cli-dev/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ulziibayarotgonbaatar/.virtualenvs/cli-dev/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ulziibayarotgonbaatar/.virtualenvs/cli-dev/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ulziibayarotgonbaatar/Workspace/echelon-backend/r2c/cli/r2c/cli/commands/run.py", line 196, in run
    env_args_dict=env_args_dict,
  File "/Users/ulziibayarotgonbaatar/.local/share/virtualenvs/cli-dev/lib/python3.7/site-packages/r2c/lib/run.py", line 348, in run_analyzer_on_local_code
    env_args_dict=env_args_dict,
  File "/Users/ulziibayarotgonbaatar/.local/share/virtualenvs/cli-dev/lib/python3.7/site-packages/r2c/lib/analyzer.py", line 392, in full_analyze_request
    specified_dependency, git_url, commit_hash, mount_folder
  File "/Users/ulziibayarotgonbaatar/.local/share/virtualenvs/cli-dev/lib/python3.7/site-packages/r2c/lib/analyzer.py", line 525, in upload_output
    self._validate_output(self._get_manifest(image_id), mount_folder)
  File "/Users/ulziibayarotgonbaatar/.local/share/virtualenvs/cli-dev/lib/python3.7/site-packages/r2c/lib/analyzer.py", line 427, in _validate_output
    manifest.output.validator(output).validate(output)
  File "/Users/ulziibayarotgonbaatar/.local/share/virtualenvs/cli-dev/lib/python3.7/site-packages/r2c/lib/manifest.py", line 141, in validator
    error_schema=self.error_extra_schema,
  File "/Users/ulziibayarotgonbaatar/.local/share/virtualenvs/cli-dev/lib/python3.7/site-packages/r2c/lib/schemas/__init__.py", line 95, in analyzer_output_validator
    spec_version = Version(output.get("spec_version", "1.0.0"))
AttributeError: 'list' object has no attribute 'get'
❌ There was an exception: 'list' object has no attribute 'get'

## Specs

- OS: [e.g. macOS Mojave, Windows 10 1809, Debian stretch]
- Python Version
- Docker Version
- Screen size (if appropriate)

**Comment by ulziibay** [comment]
cc: @cjtenny who reported it

**Comment by ulziibay** [comment]
added better exception handling for this. Closing!
