### ISSUE TITLE
The '-d' flag leads to a IndexError

### ISSUE THREAD

**Issue by AdnaneKhan** [returntocorp/cli#77]
## What happened?

Using the r2c command with the short form -d flag leads to an IndexError. The long form --analyzer-directory flag works as expected.

## What did you expect to happen?

I except the command to run correctly (as the --analyzer-directory does work).

## To reproduce

1. Run `r2c -d <analyzer_directory> CODE_DIR
2. `✘ There was an exception: list index out of range`
3. Expect to see `✔ Finished analyzing `{"code_dir": "/home/klinux/DEFCON_Training/blanket", "input_type": "LocalCode"}`. Analysis results printed to `stdout`. unless suppressed explicitly with `-q``
4. Error log is printed

## Error log

```
(venv) klinux@ubuntu:~/DEFCON_Training$ r2c run -d badwords /home/klinux/DEFCON_Training/blanket
🏃 Starting to run analyzer...
There was an exception
Traceback (most recent call last):
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/r2c/cli/__main__.py", line 15, in <module>
    cli(obj={}, prog_name="r2c")
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/r2c/cli/commands/run.py", line 189, in run
    env_args_dict = parse_remaining(env_args_string)
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/r2c/cli/util.py", line 72, in parse_remaining
    return {pair.split("=")[0]: pair.split("=")[1] for pair in pairs}
  File "/home/klinux/DEFCON_Training/venv/lib/python3.6/site-packages/r2c/cli/util.py", line 72, in <dictcomp>
    return {pair.split("=")[0]: pair.split("=")[1] for pair in pairs}
IndexError: list index out of range
✘ There was an exception: list index out of range
```

## Specs

- OS: Ubuntu 18.04 LTS
- Python Version: 3.6
- Docker Version: Docker version 19.03.1, build 74b1e89
- Screen size (if appropriate)

**Comment by AdnaneKhan** [comment]
I believe this is because the debug flag also has the short form -d.

**Comment by ulziibay** [comment]
Thanks for reporting! Being addressed in https://github.com/returntocorp/echelon-backend/pull/3509
